### ISSUE TITLE
Synchronized sub file is being stripped clean

### ISSUE THREAD

**Issue by MisterKurtz10** [smacke/subsync#30] opened 2019-05-08 14:09 UTC
I'm getting a screen like this

https://imgur.com/e41aL1Z

and the output file has a single entry.

**Comment by smacke** [comment] 2019-05-09 16:13
Hard to say more here without the video and subtitles file. The issue is that it is computing a nonsensical value for the optimal offset. I can try to find 28 days later and see what is going on in more detail, if give me a link to the subtitles.

**Comment by MisterKurtz10** [comment] 2019-05-09 21:58
I have put the file here

https://drive.google.com/open?id=1ZXfYiJdSE84HESDEOWKsrVz_jROuMS39

You won't be able to preview it as it has a password of 0123456789

**Comment by smacke** [comment] 2019-05-15 20:35
I went ahead and deleted your comment with the link but will be running some tests to figure out what is going on shortly. Thanks!

**Comment by smacke** [comment] 2019-05-21 15:40
Hi @MisterKurtz10, it looks to me like this is part of a bigger issue related to current limitations of this project. Right now subsync corrects fixed drift. This can occur, for example, if your video cuts out an intro but your subs don't (or vice versa). Despite these limitations, this handles the majority of cases pretty well. Your video is one of the exceptions -- it has a pause of some sort in the middle somewhere not present in the subs, and so the correction algorithm is barfing. I'm currently thinking about how to fix this in #10 but it will take some time I'm afraid. I'll leave this issue open so I remember to test with your video / subs once I have a working algorithm.

**Comment by Clifford10** [comment] 2019-05-21 15:45
Thanks for looking at it. I'll try with some other files to see if my luck improves.

**Comment by Clifford10** [comment] 2019-05-21 15:47
Thanks for looking into it. I'll try a few more and see if those work better.

**Comment by MisterKurtz10** [comment] 2019-05-21 15:50
Thanks for looking at it. I'll try it on other files and see if my luck improves.

**Comment by smacke** [comment] 2020-03-12 21:05
Hi @MisterKurtz10 good news! This is now fixed in the latest stable version which can be installed as follows:
`pip install git+https://github.com/smacke/subsync@STABLE`

The issue ended up being that the movie and subs were at different frame rates, which is now a case we handle properly.

I know it's been quite a while, but please consider taking another look at this project the next time you have out-of-sync subs -- the latest improvements include better character encoding detection, frame rate scaling, and support for SSA/ASS, with even more improvements planned...

**Closed by smacke** 2020-03-12 21:05 UTC
Labels: duplicate
