### ISSUE TITLE
TypeError Exception

### ISSUE THREAD

**Issue by rmassidda** [smacke/subsync#33] opened 2019-05-16 11:54 UTC
On Fedora29, running ```subsync reference.srt -i unsync.srt -o sync.srt``` raises this exception:

```
Traceback (most recent call last):
  File "/home/rmassidda/.local/bin/subsync", line 11, in <module>
    sys.exit(main())
  File "/home/rmassidda/.local/lib/python2.7/site-packages/subsync/subsync.py", line 50, in main
    reference_pipe = make_srt_speech_pipeline(args.reference_encoding or 'infer')
TypeError: make_srt_speech_pipeline() takes exactly 2 arguments (1 given)
```

**Comment by smacke** [comment] 2019-05-16 17:51
Looks like I accidentally introduced a regression, should be fixed now though if you grab the latest:

pip install git+https://github.com/smacke/subsync

**Closed by smacke** 2019-05-16 17:51 UTC
